<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>IsofileExtractor</RootNamespace>
    <AssemblyName>isoextract</AssemblyName>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <Version>0.2.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PureHDF" Version="2.1.2" />
  </ItemGroup>
  <!-- Bundle isosolfs.exe only in win-x64 publish builds -->
  <ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
    <EmbeddedResource Include="../assets/isosolfs.exe" LogicalName="isosolfs.exe" />
  </ItemGroup>
</Project>
